#name: Run App
#
#on:
#  push:
#    branches: [ main ]
#  workflow_dispatch:   # manual trigger
#
#jobs:
#  run:
#    runs-on: ubuntu-latest
#    env:
#      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-python@v5
#        with:
 #         python-version: "3.12"
#      - run: pip install -r requirements.txt
#      - run: python app.py

